{
 "title": "GKE Cluster",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_node_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_time_seconds{instance!=\"10.0.1.16:9100\"} - node_boot_time_seconds{instance!=\"10.0.1.16:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\", instance!=\"10.0.1.16:9100\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Pods by Namespace",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (namespace) (kube_pod_status_phase{phase=\"Running\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Node CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance) (avg by (mode, instance) (rate(node_cpu_seconds_total{mode!=\"idle\", instance!=\"10.0.1.16:9100\"}[5m])))*100) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Node Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(\r\n  (\r\n    node_memory_MemTotal_bytes{instance!=\"10.0.1.16:9100\"}\r\n    - node_memory_MemFree_bytes{instance!=\"10.0.1.16:9100\"}\r\n    - node_memory_Buffers_bytes{instance!=\"10.0.1.16:9100\"}\r\n    - node_memory_Cached_bytes{instance!=\"10.0.1.16:9100\"}\r\n    - node_memory_Slab_bytes{instance!=\"10.0.1.16:9100\"}\r\n  )\r\n  /\r\n  node_memory_MemTotal_bytes{instance!=\"10.0.1.16:9100\"}\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (node) (node_cpu_seconds_total{mode=\"idle\", instance!=\"10.0.1.16:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance!=\"10.0.1.16:9100\"}) / (1024^3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes{instance!=\"10.0.1.16:9100\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Running Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_running) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Pending\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out Of Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(container_oom_events_total{namespace=~\".*\", pod=~\".*\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage by Node",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance!=\"10.0.1.16:9100\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Node",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  (node_memory_MemTotal_bytes{instance!=\"10.0.1.16:9100\"} - node_memory_MemAvailable_bytes{instance!=\"10.0.1.16:9100\"})\r\n  / (1024 * 1024 * 1024)\r\n) by (instance)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=\"10.0.1.16:9100\"}[5m])*8)",
     "legendFormat": "Total received traffic"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"10.0.1.16:9100\"}[5m])*8)",
     "legendFormat": "Total transmitted traffic"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", instance!=\"10.0.1.16:9100\"}[30m])) * 100)",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "description": "Memory Stats of $nodename",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  node_memory_MemTotal_bytes{job=\"node-exporter\"}\n  - node_memory_MemFree_bytes{job=\"node-exporter\"} \n  - node_memory_Buffers_bytes{job=\"node-exporter\"} \n  - node_memory_Cached_bytes{job=\"node-exporter\"}\n)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum (node_memory_MemTotal_bytes{job=\"node-exporter\"})",
     "legendFormat": "Total Physical RAM"
    }
   ]
  },
  {
   "title": "Cluster Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (node)(rate(node_network_transmit_bytes_total{job=\"node-exporter\"}[5m])) + sum by (node)(rate(node_network_receive_bytes_total[5m])) ",
     "legendFormat": "gke-yta-cluster"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_network_transmit_bytes_total{job=\"node-exporter\"}[5m])) + sum by (instance)(rate(node_network_receive_bytes_total[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"yta\", job=\"kubelet\", image!=\"\", pod=~\"yta-be.*\"}[5m]))",
     "legendFormat": "yta-be-deployment"
    }
   ]
  },
  {
   "title": "Backend Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"yta\", job=\"kubelet\", image!=\"\", pod=~\"yta-be.*\"})",
     "legendFormat": "yta-be-deployment"
    }
   ]
  },
  {
   "title": "Weekly BE Pod CPU Usage Trend",
   "type": "timeseries",
   "description": "Current vs Last Week",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"yta\", job=\"kubelet\", image!=\"\", pod=~\"yta-be.*\"}[5m]))",
     "legendFormat": "yta-be-deployment"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{mode=\"idle\", instance!=\"10.0.1.16:9100\"}[30m] offset 7d)) * 100)",
     "legendFormat": "yta-be-deployment"
    }
   ]
  },
  {
   "title": "Weekly BE Pod Memory Usage Trend",
   "type": "timeseries",
   "description": "Current vs Last Week",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"yta\", job=\"kubelet\", image!=\"\", pod=~\"yta-be.*\"})",
     "legendFormat": "yta-be-deployment"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"yta\", job=\"kubelet\", image!=\"\", pod=~\"yta-be.*\"} offset 7d) ",
     "legendFormat": "yta-be-deployment"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod in yta Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"yta\", job=\"kubelet\", image!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod in yta Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"yta\", job=\"kubelet\", image!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts in yta Namespace",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"yta\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replica Count in yta Namespace",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"yta\"}) by (deployment)\r\nor\r\nsum(kube_deployment_spec_replicas{namespace=\"yta\"}) by (deployment)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOMKilled Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (container, namespace) (kube_pod_container_status_last_terminated_reason{container=\"django-container\", reason=\"OOMKilled\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted Pods",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"ContainerStatusUnknown\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", namespace!=\"\"}[5m])) by (namespace, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Deployment in yta Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (deployment) (\r\n  label_replace(\r\n    container_memory_working_set_bytes{container!=\"\", container!=\"POD\", namespace=\"yta\"},\r\n    \"deployment\", \r\n    \"$1\", \r\n    \"pod\", \r\n    \"^(.*?)-[a-z0-9]+-[a-z0-9]+$\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 CPU Consuming Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Memory Consuming Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod) (container_memory_usage_bytes)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pods by CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total[5m])) by (pod)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Pods by Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (pod) (container_memory_usage_bytes)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    avg(rate(container_network_receive_bytes_total[5m])) + avg(rate(container_network_transmit_bytes_total[5m])),\r\n    \"legend\", \"Cluster Network Usage\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_network_receive_bytes_total{namespace=\"yta\", pod!=\"\"}[5m]) +\r\n  rate(container_network_transmit_bytes_total{namespace=\"yta\", pod!=\"\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Bytes Received/Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m]))\r\n",
     "legendFormat": "received-bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m]))",
     "legendFormat": "sent-bytes"
    }
   ]
  },
  {
   "title": "Top 10 Throttle Pods",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(10, avg by (pod) (topk(10, (rate(container_cpu_cfs_throttled_periods_total[5m]))))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure on Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Used Space",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=~\".*\"}) by (persistentvolumeclaim)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOMKilled Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by (container, namespace) (kube_pod_container_status_last_terminated_reason{container=\"django-container\", reason=\"OOMKilled\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted Pods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{reason=\"ContainerStatusUnknown\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk I/O for Pods in yta Namespace",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{namespace=\"yta\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Network Egress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"yta\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 165 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n    count(kube_deployment_created),\r\n    \"legend\", \"Deployments\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n    count(kube_daemonset_created),\r\n    \"legend\", \"DaemonSets\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n    count(kube_namespace_created),\r\n    \"legend\", \"Namespaces\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n    sum(kube_persistentvolume_info),\r\n    \"legend\", \"PVs\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n    count(kube_replicaset_created),\r\n    \"legend\", \"ReplicaSets\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n    sum(kube_persistentvolumeclaim_info),\r\n    \"legend\", \"PVCs\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(\r\n    sum(rate(container_network_receive_bytes_total{job=\"kubelet\", pod!=\"\"}[5m])),\r\n    \"legend\", \"Network Receive Bytes\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n    sum(rate(container_network_transmit_bytes_total{job=\"kubelet\", pod!=\"\"}[5m])),\r\n    \"legend\", \"Network Transmit Bytes\", \"\", \"\"\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(pod) (kube_pod_container_resource_limits{pod=~\".+\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (kube_pod_container_resource_limits{pod=~\".+\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(pod) (kube_pod_container_resource_requests{pod=~\".+\", resource=\"cpu\", unit=\"core\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 188 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by(pod) (kube_pod_container_resource_requests{pod=~\".+\", resource=\"memory\", unit=\"byte\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", container=~\".*\"}[5m])) by (container, image)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}